# Generated by Django 5.1.7 on 2025-03-29 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym_mantenimiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='encargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gym_mantenimiento.maquina'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tipo_incidente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gym_mantenimiento.tipoincidente'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='urgencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gym_mantenimiento.urgencia'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gym_mantenimiento.zona'),
        ),
    ]
