# Generated by Django 5.1.7 on 2025-03-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('ENCARGADO', 'Encargado del Gimnasio'), ('TECNICO', 'Técnico de Mantenimiento')], max_length=20, null=True),
        ),
    ]
